// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetHelloHandlerFunc turns a function with the right signature into a get hello handler
type GetHelloHandlerFunc func(GetHelloParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHelloHandlerFunc) Handle(params GetHelloParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetHelloHandler interface for that can handle valid get hello params
type GetHelloHandler interface {
	Handle(GetHelloParams, interface{}) middleware.Responder
}

// NewGetHello creates a new http.Handler for the get hello operation
func NewGetHello(ctx *middleware.Context, handler GetHelloHandler) *GetHello {
	return &GetHello{Context: ctx, Handler: handler}
}

/* GetHello swagger:route GET /hello home getHello

GetHello get hello API

*/
type GetHello struct {
	Context *middleware.Context
	Handler GetHelloHandler
}

func (o *GetHello) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHelloParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
