// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"hello/models"
)

// GetHelloReader is a Reader for the GetHello structure.
type GetHelloReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHelloReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHelloOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHelloOK creates a GetHelloOK with default headers values
func NewGetHelloOK() *GetHelloOK {
	return &GetHelloOK{}
}

/* GetHelloOK describes a response with status code 200, with default header values.

Hello
*/
type GetHelloOK struct {
	Payload *models.WelcomingMessage
}

func (o *GetHelloOK) Error() string {
	return fmt.Sprintf("[GET /hello][%d] getHelloOK  %+v", 200, o.Payload)
}
func (o *GetHelloOK) GetPayload() *models.WelcomingMessage {
	return o.Payload
}

func (o *GetHelloOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WelcomingMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
