// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHelloParams creates a new GetHelloParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHelloParams() *GetHelloParams {
	return &GetHelloParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHelloParamsWithTimeout creates a new GetHelloParams object
// with the ability to set a timeout on a request.
func NewGetHelloParamsWithTimeout(timeout time.Duration) *GetHelloParams {
	return &GetHelloParams{
		timeout: timeout,
	}
}

// NewGetHelloParamsWithContext creates a new GetHelloParams object
// with the ability to set a context for a request.
func NewGetHelloParamsWithContext(ctx context.Context) *GetHelloParams {
	return &GetHelloParams{
		Context: ctx,
	}
}

// NewGetHelloParamsWithHTTPClient creates a new GetHelloParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHelloParamsWithHTTPClient(client *http.Client) *GetHelloParams {
	return &GetHelloParams{
		HTTPClient: client,
	}
}

/* GetHelloParams contains all the parameters to send to the API endpoint
   for the get hello operation.

   Typically these are written to a http.Request.
*/
type GetHelloParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get hello params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHelloParams) WithDefaults() *GetHelloParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get hello params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHelloParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get hello params
func (o *GetHelloParams) WithTimeout(timeout time.Duration) *GetHelloParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hello params
func (o *GetHelloParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hello params
func (o *GetHelloParams) WithContext(ctx context.Context) *GetHelloParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hello params
func (o *GetHelloParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get hello params
func (o *GetHelloParams) WithHTTPClient(client *http.Client) *GetHelloParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get hello params
func (o *GetHelloParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHelloParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
